services:
  - type: web
    name: fsociety-relay
    env: rust
    runtime: rust
    buildCommand: cargo build --release --manifest-path render-server/Cargo.toml
    startCommand: ./render-server/target/release/render-server
    plan: free
    envVars:
      - key: PORT
        value: 10000
